language: android
android:
  components:
    - android-23
    - build-tools-23.0.3
  licenses:
    - 'android-sdk-license-.+'

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

script:
   - ./gradlew build
